spring:
  mvc:
    static-path-pattern: "/resources/static/**"
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      maxFileSize: 20MB
      maxRequestSize: 100MB
  devtools:
    livereload:
      enabled: true
server:
  compression:
    enabled: true
  http2:
    enabled: true  
  port: 8080
  servlet:
    context-path: /
  error:
    path: /error
    whitelabel:
      enabled: false
  tomcat:
    use-relative-redirects: true
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
  forward-headers-strategy : native
    
--- #local
spring:
  config:
    activate:
      on-profile: local
  thymeleaf:
    cache: false
  primary:
    datasource:
      hikari:
        jdbc-url: jdbc:mariadb://localhost:3306/acafe?useSSL=false
        username: acafe
        password: acafe
        driver-class-name: org.mariadb.jdbc.Driver
        minimumIdle: 10
        maximumPoolSize: 50
        connectionTimeout: 5000
        connectionTestQuery: SELECT 1
        data-source-properties:
          useLocalSessionState: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
logging:
  config: classpath:logback-local.xml
  
--- #dev
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  primary:
    datasource:
      hikari:
        jdbc-url: jdbc:mariadb://localhost:3306/acafe?useSSL=false
        username: acafe
        password: acafe
        driver-class-name: org.mariadb.jdbc.Driver
        minimumIdle: 10
        maximumPoolSize: 50
        connectionTimeout: 5000
        connectionTestQuery: SELECT 1
        data-source-properties:
          useLocalSessionState: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        hbm2ddl.auto: create
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MariaDB103Dialect
logging:
  config: classpath:logback-local.xml
  
--- #prod
spring:
  config:
    activate:
      on-profile: prod
  thymeleaf:
    cache: true
  primary:
    datasource:
      hikari:
        jdbc-url: jdbc:mariadb://localhost:3306/acafe?useSSL=false
        username: acafe
        password: acafe
        driver-class-name: org.mariadb.jdbc.Driver
        minimumIdle: 10
        maximumPoolSize: 50
        connectionTimeout: 5000
        connectionTestQuery: SELECT 1
        data-source-properties:
          useLocalSessionState: true
          cacheServerConfiguration: true
          elideSetAutoCommits: true
          maintainTimeStats: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
logging:
  config: classpath:logback-prod.xml